# Generated by Django 5.0.6 on 2024-07-04 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email Address')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Donation Name')),
                ('category', models.CharField(choices=[('Clothing', 'Clothing'), ('Hygiene Products', 'Hygiene Products'), ('School Supplies', 'School Supplies'), ('Household items', 'Household items'), ('Medical Supplies', 'Medical Supplies'), ('Toys and Games', 'Toys and Games'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Books and Magazines', 'Books and Magazines'), ('Others', 'Others')], default='Others', max_length=20)),
                ('count', models.PositiveIntegerField(verbose_name='Item Count')),
                ('image', models.ImageField(blank=True, null=True, upload_to='donation_images/')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('volunteer_category', models.CharField(choices=[('CS', 'Companionship and support'), ('MT', 'Mentoring and Tutoring'), ('AEM', 'Activities or event management'), ('HWS', 'Health and Wellness support'), ('AO', 'Advocacy and outreach'), ('SP', 'Special Projects'), ('O', 'Others')], default='O', max_length=3)),
                ('volunteer_details', models.TextField(blank=True, verbose_name='Volunteer Details')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.donor')),
            ],
        ),
    ]
