# Generated by Django 5.0.6 on 2024-07-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donee',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('approved', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Approved')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('venue', models.CharField(max_length=200, verbose_name='Venue')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('category', models.CharField(choices=[('Companionship and support', 'Companionship and support'), ('Mentoring and Tutoring', 'Mentoring and Tutoring'), ('Activities or event management', 'Activities or event management'), ('Health and Wellness support', 'Health and Wellness support'), ('Advocacy and outreach', 'Advocacy and outreach'), ('Special Projects', 'Special Projects'), ('Others', 'Others')], default='Others', max_length=50)),
                ('description', models.TextField(verbose_name='Description')),
                ('donee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.donee')),
            ],
        ),
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Need Name')),
                ('category', models.CharField(choices=[('Clothing', 'Clothing'), ('Hygiene Products', 'Hygiene Products'), ('School Supplies', 'School Supplies'), ('Household items', 'Household items'), ('Medical Supplies', 'Medical Supplies'), ('Toys and Games', 'Toys and Games'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Books and Magazines', 'Books and Magazines'), ('Others', 'Others')], default='Others', max_length=20)),
                ('count', models.PositiveIntegerField(verbose_name='Item Count')),
                ('status', models.CharField(choices=[('Urgent', 'Urgent'), ('Not Urgent', 'Not Urgent')], default='Not Urgent', max_length=10)),
                ('donee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhapp.donee')),
            ],
        ),
    ]
